import React from "react";
import { Convergence } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import PropTypes from "prop-types";

export const metadata = {
  title: "Money Manager",
  description: "Generated by create next app",
};

const convergence = Convergence({ weight: "400", subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={convergence.className}>{children}</body>
    </html>
  );
}
RootLayout.propTypes = {
  children: PropTypes.element,
};
