import React from "react";
import { Convergence } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import PropTypes from "prop-types";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import DatabaseProvider from "@/contexts/DatabaseContext";

export const metadata = {
  title: "Money Manager",
  description: "Generated by create next app",
};

const convergence = Convergence({ weight: "400", subsets: ["latin"] });
export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={convergence.className}>
        <DatabaseProvider>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </DatabaseProvider>
      </body>
    </html>
  );
}
RootLayout.propTypes = {
  children: PropTypes.element,
  params: PropTypes.object,
};
